<div class="row">
    <div role="complementary" class="col-md-2">
        <nav class="bs-docs-sidebar hidden-print hidden-sm hidden-xs affix">
            <ul class="nav bs-docs-sidenav">
                <?
                foreach($this->examples AS $key => $example) {
                    ?>
                    <li><a href="#<?php echo $example['title'] ?>"><?php echo $example['title'] ?></a></li><?
                }
                ?>

            </ul>
            <a class="back-to-top" href="#top"> Back to top </a>
        </nav>
    </div>
    <div role="main" class="col-md-10">

        <?
        foreach($this->examples AS $key => $example){
            ?>
            <a id="<?php echo $example['title']?>" class="anchorjs-link anchor" href="#<?php echo $example['title']?>"
               aria-label="Anchor link for: <?php echo $example['title']?>"></a>
            <h2  class="page-header"><?php echo $example['title']?></h2>

            <pre class="pre-scrollable">
                <code class="language-php">
                    <?php echo $example['code']?>
                </code>
            </pre>
            <div class="panel panel-default">
                <!-- Default panel contents -->
                <div class="panel-heading"><?php echo $example['describtion']?></div>
                    <?php echo $example['sample']?>
            </div>
            <?
        }

        ?>
    </div>
</div>