<?
$item = $graphNode;
?>
<h2><? echo $graphNodeType;?> :: <a href="<? echo $this->url("graphnode", array("id" => $graphNode->getField("id"))); ?>"><?echo $graphNodeTitle?></a></h2>
<table class="table-bordered table table-responsive">
    <thead class="thead-default">
    <tr>
        <td><? echo $this->translate("Key");?> </td>
        <td><? echo $this->translate("Value");?> </td>
    </tr>

    </thead>
    <tbody>
    <?
    /* @var $item \FbBasic\GraphNodes\GraphInterface */
    $fieldnames = $item->getFieldNames();
    $edges = $item->getObjectEdges();
    echo '"'.implode('","',$fieldnames).'"';
    foreach ($fieldnames AS $fieldName) {
        $field = $item->getField($fieldName);

        ?>
        <tr>
            <td><?
                if(isset($edges[$fieldName])){
                   ?><a href="<? echo $this->url("graphedge",array("id"=>$item->getField("id"),"edge"=>$fieldName));?>"><? echo $fieldName;?></a><?
                }
                else{
                    echo $fieldName;
                }
                 ?></td>
            <td>
                <? echo $this->graphfield($fieldName,$field); ?>&nbsp;
            </td>
        </tr>
        <?
    }
    /*
    if(isset($graphEdges)){
        foreach ($graphEdges AS $edge) {
            ?>
            <tr>
                <td><? echo $edge['key']; ?></td>
                <td>
                    <a href="<? echo $this->url("graphedge",array("id"=>$item->getField("id"),"edge"=>$edge['key']));?>"><? echo $edge['count'];?></a>&nbsp;
                </td>
            </tr>
            <?
        }
    }
    */

    ?>
    </tbody>
</table>
