<?php echo $this->doctype(); ?>

<html lang="de">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Florian Degenhardt">
    <meta name="publisher" content="Florian Degenhardt">
    <meta name="copyright" content="Florian Degenhardt">
    <meta name="description" content="Example Page for Facebook GRap Api">
    <meta name="keywords" content="Facebook, Graph, Api, Examples, Zend Framework 2, Modul">
    <meta name="page-topic" content="Api">
    <meta http-equiv="content-language" content="de">
    <meta name="robots" content="index, follow">

    <title>Facebook Graph Example Page</title>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <?php

    //Loading Resources
    if (defined("APPLICATION_ENV") && APPLICATION_ENV === 'development') {
        //All Stylesheets
        $this->headLink()->appendStylesheet($this->basePath('css/bootstrap.css'));
        $this->headLink()->appendStylesheet($this->basePath('css/bootstrap-theme.css'));
        //$this->view->headLink()->appendStylesheet('font-awesome/css/font-awesome.min.css');
        //Javascripts
        $this->headScript()->appendFile($this->basePath('js/lib.js', 'text/javascript'));
        $this->headScript()->appendFile($this->basePath('js/frontend.js', 'text/javascript'));
    } else {
        //All Stylesheets
        $this->headLink()->appendStylesheet($this->basePath('css/bootstrap.min.css'));
        //Javascripts
        $this->headScript()->appendFile($this->basePath('js/bootstrap.min.js'));
    }



    $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath('favicon.ico')));
    //->prependStylesheet($this->basePath('css/style.css'))
    //->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
    //->appendStylesheet($this->basePath('css/bootstrap.min.css'));

    echo $this->headLink(); ?>



    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <?php echo $this->headScript(); ?>


</head>
<body>

<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Facebook Api Example</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <?php echo $this->navigation('navigation')->menu()->setMaxDepth(0)->setRenderParents(true)->setUlClass('nav navbar-nav'); ?>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>
<div class="container">
    <div id="breadcrumbs">
        <?php echo $this->navigation('navigation')->breadcrumbs()->setMinDepth(0)->setSeparator('&nbsp;&Gt;&nbsp;'); ?>
    </div>
    <?php echo $this->content; ?>
</div>
<?php echo $this->inlineScript() ?>
</body>
</html>
